// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkHF6RHk9SZxaoLGzFhw8MV0iOciRjg4',
    appId: '1:1049223436785:web:98f687a0a06dacfe9b4c50',
    messagingSenderId: '1049223436785',
    projectId: 'griot-app-project',
    authDomain: 'griot-app-project.firebaseapp.com',
    storageBucket: 'griot-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABrdQej37R7SY6Q_WYmLY0-SDIXkAv0BM',
    appId: '1:1049223436785:android:990672dfaf68af889b4c50',
    messagingSenderId: '1049223436785',
    projectId: 'griot-app-project',
    storageBucket: 'griot-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBlN9LTIDozdwwvzSZ8M8JeywwpAq1-g',
    appId: '1:1049223436785:ios:4d2f152771a5421e9b4c50',
    messagingSenderId: '1049223436785',
    projectId: 'griot-app-project',
    storageBucket: 'griot-app-project.firebasestorage.app',
    iosBundleId: 'com.example.griotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBlN9LTIDozdwwvzSZ8M8JeywwpAq1-g',
    appId: '1:1049223436785:ios:4d2f152771a5421e9b4c50',
    messagingSenderId: '1049223436785',
    projectId: 'griot-app-project',
    storageBucket: 'griot-app-project.firebasestorage.app',
    iosBundleId: 'com.example.griotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArkHF6RHk9SZxaoLGzFhw8MV0iOciRjg4',
    appId: '1:1049223436785:web:2130d923393485979b4c50',
    messagingSenderId: '1049223436785',
    projectId: 'griot-app-project',
    authDomain: 'griot-app-project.firebaseapp.com',
    storageBucket: 'griot-app-project.firebasestorage.app',
  );
}
